VERSION 0.8

IMPORT ../../common AS common

SETUP:
    FUNCTION
    RUN micromamba install -n base -c conda-forge -y jupyterlab jupyterhub-singleuser jupyter-server-proxy ipykernel ipywidgets
    RUN micromamba -n base run jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
    COPY frontend/jupyter/update-gdds.sh frontend/jupyter/launch-jupyter-lab.sh /usr/local/bin/
    RUN update-gdds.sh
    CMD ["launch-jupyter-lab.sh"]

INSTALL_GDDS_EXTENSION:
    FUNCTION
    COPY +build-gdds-extension/gdds-0.1.0-py3-none-any.whl ./
    RUN micromamba -n base run pip install gdds-0.1.0-py3-none-any.whl
    RUN rm gdds-0.1.0-py3-none-any.whl
    RUN micromamba -n base run jupyter labextension enable gdds
