VERSION 0.8

IMPORT ../../common AS common

SETUP:
    FUNCTION
    RUN micromamba install -n base -c conda-forge -y jupyterlab jupyterhub-singleuser jupyter-server-proxy ipykernel ipywidgets
    RUN micromamba -n base run jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
    COPY frontend/jupyter/update-gdds.sh frontend/jupyter/entrypoint.sh /usr/local/bin/
    RUN update-gdds.sh
    ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
    CMD ["jupyter", "lab", "--ip=0.0.0.0", "--port=8888"]
