VERSION 0.8

IMPORT ../../common AS common

SETUP:
    FUNCTION
    RUN micromamba install -n base -c conda-forge -y jupyterlab jupyterhub-singleuser jupyter-server-proxy ipykernel ipywidgets
    RUN micromamba -n base run jupyter labextension disable "@jupyterlab/apputils-extension:announcements"
    COPY frontend/jupyter/update-gdds.sh frontend/jupyter/entrypoint.sh /usr/local/bin/
    RUN update-gdds.sh
    ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]
    CMD ["micromamba", "-n", "base", "run", "jupyter", "lab", "--ip=0.0.0.0", "--port=8888"]

INSTALL_GDDS_EXTENSION:
    FUNCTION
    COPY +build-gdds-extension/gdds-0.1.0-py3-none-any.whl ./
    RUN micromamba -n base run pip install gdds-0.1.0-py3-none-any.whl
    RUN rm gdds-0.1.0-py3-none-any.whl
    RUN micromamba -n base run jupyter labextension enable gdds
