VERSION 0.8

SETUP:
    FUNCTION
    ARG COMPUTE_SPECIFIC_CHANNELS
    ARG COMPUTE_SPECIFIC_PACKAGES
    RUN micromamba install -n base -c conda-forge $COMPUTE_SPECIFIC_CHANNELS -y r-base r-tidyverse r-amelia r-rpart.plot r-irkernel r-factoextra $COMPUTE_SPECIFIC_PACKAGES

SETUP_CPU:
    FUNCTION
    DO +SETUP

JUPYTER_POST_INSTALL:
    FUNCTION
    RUN echo "IRkernel::installspec()" | micromamba -n base run R --no-save 
