name: Earthly +all

on:
  push:
    branches: [ main ]
    tags: [ '*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: [all-python-cpu, all-python-cuda, all-r, all-rust, full-jupyter]
    env:
      FORCE_COLOR: 1
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-codeql: 'true'
        remove-haskell: 'true'
        overprovision-lvm: 'true'
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.0
    - uses: actions/checkout@v4
    - name: Login to GitHub Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Get branch names.
      id: branch-names
      uses: tj-actions/branch-names@v8
    - name: Run build
      env:
        GDDS_REPOSITORY_URL: ${{ secrets.GDDS_REPOSITORY_URL }}
      run: earthly --secret GDDS_REPOSITORY_URL --ci --push +${{ matrix.image }} --REGISTRY ghcr.io/thm-mni-ii/ml-docker-images --VERSION ${{ github.ref_name }}
